# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('name', models.CharField(max_length=256)),
                ('industry', models.CharField(choices=[('food', 'Food'), ('beverages', 'Beverages'), ('steel', 'Steel'), ('automotive', 'Automotive'), ('electronics', 'Electronics')], max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=256)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='supplychain.Supplier'),
        ),
    ]
