# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.Supplier'),
        ),
    ]
