# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_auto_20170302_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='certificates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='partners',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
