# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_auto_20170305_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.Product'),
        ),
    ]
