# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0005_auto_20170309_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_of_parts',
        ),
        migrations.AlterField(
            model_name='part',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='supplychain.Product'),
        ),
    ]
