# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0007_auto_20170309_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('comment', models.CharField(max_length=256, null=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpart', to='supplychain.Part')),
            ],
        ),
    ]
