# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0008_subpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
